### ISSUE TITLE
Creating an English lexeme works, but crashes

### ISSUE THREAD

**Issue by blinry** [Nudin/LexData#3]
When using `get_or_create_lexeme` to create new English lexemes, the lexeme is created, but the program then crashes.

Program:

```
import LexData
from LexData.languages import en
repo = LexData.WikidataSession("Blinry", "foobar")
l = LexData.get_or_create_lexeme(repo, "watermelon", en, "Q1084")
```

Error:

```
Traceback (most recent call last):
  File "mod.py", line 18, in <module>
    l = LexData.get_or_create_lexeme(repo, "watermelon", en, "Q1084")
  File "/usr/lib/python3.7/site-packages/LexData/__init__.py", line 532, in get_or_create_lexeme
    return create_lexeme(repo, lemma, lang, catLex)
  File "/usr/lib/python3.7/site-packages/LexData/__init__.py", line 580, in create_lexeme
    lexeme.createClaims(claims)
  File "/usr/lib/python3.7/site-packages/LexData/__init__.py", line 446, in createClaims
    self.__setClaims__(self["id"], claims)
  File "/usr/lib/python3.7/site-packages/LexData/__init__.py", line 457, in __setClaims__
    for cle, values in claims.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by blinry** [comment]
Thanks for fixing these so quickly! <3
