### ISSUE TITLE
Can't create lexemes in unsupported languages

### ISSUE THREAD

**Issue by blinry** [Nudin/LexData#4]
I want to enter lexemes in a language that doesn't have an ISO code yet, like [L1](https://www.wikidata.org/wiki/Lexeme:L1). LexData crashes if I try that. I wonder if there would be a workaround?

Program:

```
import LexData
tok = LexData.Language("mis-x-Q36846", "Q36846")
repo = LexData.WikidataSession("Blinry", "foobar")
l = LexData.get_or_create_lexeme(repo, "ike", tok, "Q34698")
```

Error:

```
Traceback (most recent call last):
  File "mod.py", line 17, in <module>
    l = LexData.get_or_create_lexeme(repo, "ike", tok, "Q34698")
  File "/usr/lib/python3.7/site-packages/LexData/__init__.py", line 519, in get_or_create_lexeme
    for item in DATA["search"]:
KeyError: 'search'
```

**Comment by Nudin** [comment]
@blinry There is another bug connected to languages without ISO code. So better wait for that to be fixed too!
